apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deploy
  namespace: custom-ns
  labels:
    name: db-deploy

spec:
  replicas: 1 # no. of instances
  selector:
    matchLabels:
      db: mysql # required, can be same as template.metadata.labels attrs

  template: # template pod that will be deployed
    metadata:
      name: db-pod
      labels:
        name: db-pod
        db: mysql
        
    spec:
      containers:
        - name: db-container
          image: stackupiss/northwind-db:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service

metadata:
  name: db-service
  namespace: custom-ns
  labels:
    name: db-service

spec:
  type: ClusterIP     # ClusterIP/NodePort/LoadBalancer
  selector:
    name: db-pod      # select db-pods specifically
  ports:
  - port: 3306        # service's port
    targetPort: 3306  # container's port
