apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name:  openweather-svc-entry
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.external_api }}
  ports:
  - number: 80
    protocol: http
    name : http
  - number: 443
    protocol: https
    name : https
  location: MESH_EXTERNAL
  resolution: DNS