apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name:  {{ include "weatherapp.fullname" . }}
  namespace: default
spec:
  hosts:
  - {{ .Values.external_api}}
  ports:
  - number: 80
    protocol: http
    name : http
  location: MESH_EXTERNAL
  resolution: DNS